### ISSUE TITLE
Investigate possibility to use this driver from Rancher

### ISSUE THREAD

**Issue by anton-sidelnikov** [opentelekomcloud/docker-machine-opentelekomcloud#13]
- Create ECS with EIP
- UP rancher on ECS
- Setup nginx to expose rancher web ui
- Create configuration for docker-machine-opentelekomcloud

**Comment by lego963** [comment]
tf+ansible, am I right?

**Comment by lego963** [comment]
Rancher. Needs to be discussed

**Comment by outcatcher** [comment]
Depends  on #18

**Comment by outcatcher** [comment]
Done, works in [v0.2.2 beta 1](https://github.com/opentelekomcloud/docker-machine-opentelekomcloud/releases/download/0.2.2b1/docker-machine-driver-otc-0.2.2b1-linux-amd64.tgz)
