### ISSUE TITLE
[Rancher] nil pointer

### ISSUE THREAD

**Issue by lego963** [opentelekomcloud/docker-machine-opentelekomcloud#14]
Problem description: `Auth fail and it caused by clouds.yaml file`
Tool version: `0.1.2-linux-amd64`
Rancher version: `v2.2.4`
Rancher report: got from api 
`{`
    `"message": "Error creating machine: Error in driver during machine creation: Panic in the driver:` 
    `runtime error: invalid memory address or nil pointer dereference",`
    `"reason": "Error",`
    `"status": "False",`
    `"type": "Provisioned"`
`}`

**Comment by outcatcher** [comment]
Caused with https://github.com/gophercloud/utils/issues/115
