### ISSUE TITLE
Create Image for host VMs

### ISSUE THREAD

**Issue by outcatcher** [opentelekomcloud/docker-machine-opentelekomcloud#2]
Creating `Debian` 9/10 VM takes about 2 minutes.

I purpose to create and upload minimalistic host VM image containing only `cloud-init`, `dockerd` and its requirements.

**Comment by gtema** [comment]
we can prepare it with diskimage-builder for testing purposes. After we decide it's ok, we can pass it to ImageFactory for publishing

**Comment by outcatcher** [comment]
Bottleneck of machine creation seems to be not connected with system boot, so this issue can be postponed for now
