### ISSUE TITLE
Missing SG incoming rules in default docker-machine-grp

### ISSUE THREAD

**Issue by kucerakk** [opentelekomcloud/docker-machine-opentelekomcloud#55]
When creating a cluster without defining custom security group the driver creates a default SG docker-machine-grp which contains only two incoming rules: tcp/22 and tcp/2376 (marked with green in the screenshot)
During the installation the installer complains about connection refused on the following ports: tcp/2379, tcp/6443, tcp/10250 (marked with red in the screenshot). Without adding these ports to the SG the cluster creation gets stuck.

![image](https://user-images.githubusercontent.com/8899650/108996820-2c4c2f00-769f-11eb-96e3-905ae5c31d06.png)

**Comment by anton-sidelnikov** [comment]
Done in #74
