### ISSUE TITLE
user-data capability

### ISSUE THREAD

**Issue by agepi477** [opentelekomcloud/docker-machine-opentelekomcloud#69]
Hi,

I downloaded v.2.4.0 and tested it on a standalone Ubuntu and I have a question regarding the user-data parameters.
As "--user-data-file" works just fine with a local YAML file I couldn't figure out how the "--user-data-raw" works. In the documentation I found the description that it expects the user-data in a single line but I couldn't find a way how to do that. Would be great to get a hint how that works.

Best regards

Hendrik

**Comment by outcatcher** [comment]
Hi @agepi477, `--user-data-raw` is originally designed to be used with the Rancher, allowing to pass _contents_ of the user data file, not a _path_ to the file. We are thinking about merging those two flags into a single one in the future (#65).
I hope, this answers your question :slightly_smiling_face:

**Comment by agepi477** [comment]
﻿Hi,

thanks for your quick reply. That’s fine. Would be good to have something similar to the ECS creation wizard on the OTC console. Can you make an estimation what „future“ means?

Best regards

Hendrik

**Comment by outcatcher** [comment]
What exactly do you mean by "something similar to the ECS creation wizard"?

**Comment by agepi477** [comment]
When you deploy a ECS via OTC Web Console you can inject user data using this dialogue: 
[ https://docs.otc.t-systems.com/usermanual/ecs/en-us_topic_0032380449.html | https://docs.otc.t-systems.com/usermanual/ecs/en-us_topic_0032380449.html ] 

I think it would be grat to have something similar in the rancher node template for the OTC. 
In the vSphere node driver this is already implemented like that: 
Cheers, Hendrik 

Von: "Anton Kachurin" ***@***.***> 
An: "opentelekomcloud/docker-machine-opentelekomcloud" ***@***.***> 
CC: "Hendrik Praedicow" ***@***.***>, "Mention" ***@***.***> 
Gesendet: Donnerstag, 18. März 2021 08:34:48 
Betreff: Re: [opentelekomcloud/docker-machine-opentelekomcloud] user-data capability (#69) 






What exactly do you mean by "something similar to the ECS creation wizard"?

**Comment by outcatcher** [comment]
@agepi477 We already planned to implement this in the OTC node driver UI :slightly_smiling_face:

**Comment by agepi477** [comment]
This is great to hear. Thank you very much for your time. 


Von: "Anton Kachurin" ***@***.***> 
An: "opentelekomcloud" ***@***.***> 
CC: "Hendrik Praedicow" ***@***.***>, "Mention" ***@***.***> 
Gesendet: Donnerstag, 18. März 2021 12:59:47 
Betreff: Re: [opentelekomcloud/docker-machine-opentelekomcloud] user-data capability (#69) 





[ https://github.com/agepi477 | @agepi477 ] We already planned to implement this in the OTC node driver UI 🙂
