### ISSUE TITLE
Backward compatibility

### ISSUE THREAD

**Issue by outcatcher** [opentelekomcloud/docker-machine-opentelekomcloud#9]
Migration to new version of docker-machine driver for OTC should be seamless
Include:
#22 
#23 
#24

**Comment by lego963** [comment]
https://github.com/Huawei/DockerMachineDriver4OTC

**Comment by lego963** [comment]
CLI option | Environment variable | Default
-- | -- | --
--otc-access-key-id | ACCESS_KEY_ID | -
--otc-access-key-key | ACCESS_KEY_SECRET | -
--otc-available-zone | AVAILABLE_ZONE | -
--otc-service-endpoint | SERVICE_ENDPOINT | -
--otc-bandwidth-size | BANDWIDTH_SIZE | 10
--otc-bandwidth-type | BANDWIDTH_TYPE | PER
--otc-elasticip-type | ELASTICIP_TYPE | 5_bgp
--otc-root-volume-size | ROOT_VOLUME_SIZE | 40
--otc-root-volume-type | ROOT_VOLUME_TYPE | SATA
--otc-elastic-ip | ELASTIC_IP | 1

It is taken from `https://github.com/Huawei/DockerMachineDriver4OTC/blob/master/README.md`

**Comment by outcatcher** [comment]
Found incompatibilities to be fixed

**Comment by outcatcher** [comment]
Done
